/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as PlaygroundRouteImport } from './routes/playground'
import { Route as OfiRouteImport } from './routes/ofi'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntegrationRouteImport } from './routes/integration'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiT0ProviderSplatRouteImport } from './routes/api/t0/provider/$'

const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRoute = PlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const OfiRoute = OfiRouteImport.update({
  id: '/ofi',
  path: '/ofi',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationRoute = IntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiT0ProviderSplatRoute = ApiT0ProviderSplatRouteImport.update({
  id: '/api/t0/provider/$',
  path: '/api/t0/provider/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/integration': typeof IntegrationRoute
  '/login': typeof LoginRoute
  '/ofi': typeof OfiRoute
  '/playground': typeof PlaygroundRoute
  '/provider': typeof ProviderRoute
  '/sandbox': typeof SandboxRoute
  '/api/login': typeof ApiLoginRoute
  '/api/t0/provider/$': typeof ApiT0ProviderSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/integration': typeof IntegrationRoute
  '/login': typeof LoginRoute
  '/ofi': typeof OfiRoute
  '/playground': typeof PlaygroundRoute
  '/provider': typeof ProviderRoute
  '/sandbox': typeof SandboxRoute
  '/api/login': typeof ApiLoginRoute
  '/api/t0/provider/$': typeof ApiT0ProviderSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/integration': typeof IntegrationRoute
  '/login': typeof LoginRoute
  '/ofi': typeof OfiRoute
  '/playground': typeof PlaygroundRoute
  '/provider': typeof ProviderRoute
  '/sandbox': typeof SandboxRoute
  '/api/login': typeof ApiLoginRoute
  '/api/t0/provider/$': typeof ApiT0ProviderSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs'
    | '/integration'
    | '/login'
    | '/ofi'
    | '/playground'
    | '/provider'
    | '/sandbox'
    | '/api/login'
    | '/api/t0/provider/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/integration'
    | '/login'
    | '/ofi'
    | '/playground'
    | '/provider'
    | '/sandbox'
    | '/api/login'
    | '/api/t0/provider/$'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/integration'
    | '/login'
    | '/ofi'
    | '/playground'
    | '/provider'
    | '/sandbox'
    | '/api/login'
    | '/api/t0/provider/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  IntegrationRoute: typeof IntegrationRoute
  LoginRoute: typeof LoginRoute
  OfiRoute: typeof OfiRoute
  PlaygroundRoute: typeof PlaygroundRoute
  ProviderRoute: typeof ProviderRoute
  SandboxRoute: typeof SandboxRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiT0ProviderSplatRoute: typeof ApiT0ProviderSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofi': {
      id: '/ofi'
      path: '/ofi'
      fullPath: '/ofi'
      preLoaderRoute: typeof OfiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integration': {
      id: '/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof IntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/t0/provider/$': {
      id: '/api/t0/provider/$'
      path: '/api/t0/provider/$'
      fullPath: '/api/t0/provider/$'
      preLoaderRoute: typeof ApiT0ProviderSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  IntegrationRoute: IntegrationRoute,
  LoginRoute: LoginRoute,
  OfiRoute: OfiRoute,
  PlaygroundRoute: PlaygroundRoute,
  ProviderRoute: ProviderRoute,
  SandboxRoute: SandboxRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiT0ProviderSplatRoute: ApiT0ProviderSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
